### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by yardenshoham**
Added a Dockerfile so `jsonwebtoken.github.io` could be deployed as a container!

### CODE REVIEW

**Comment by yardenshoham** [comment]
@Sambego Can you review/approve/merge?

**Comment by Sambego** [comment]
Hey @yardenshoham, thanks for this pr.

Can you help me understand whey we would need this Docker file, as currently JWT.io is not deployed trough Docker?

**Comment by yardenshoham** [comment]
Maybe if there's a need to deploy an instance on a fresh machine and the machine only has docker (no node/nginx).

**Comment by Sambego** [comment]
I don't think we need this docker file in this repo at this moment as we're not using Docker to deploy jwt.io.

If anybody wan't to deploy a local instance of this tool with docker, they are free to fork the repo and add the dockerfile in their fork.

**Pull request closed without merging**
