### PR TITLE
Add C language JWT library

### PR DESCRIPTION
**Pull request by benmcollins**
Signed-off-by: Ben Collins <ben@cyphre.com>

### CODE REVIEW

**Comment by benmcollins** [comment]
Merged with latest master branch.

**Comment by benmcollins** [comment]
Any chance of getting this merged so I don't have to keep fixing the conflicts?

**Comment by woloski** [comment]
Hi Ben,

It will. We do it on a batch every friday :)

**Comment by pose** [comment]
@benmcollins just manually merged your changes, welcome aboard!

**Pull request closed without merging**
