### PR TITLE
Add SwiftyJWT to JWT library list

### PR DESCRIPTION
**Pull request by Wstunes**
I've made a Swift library which supports JWT encoding and decoding with Swift language. And it also supports all claims checking. Please review it.

### CODE REVIEW

**Comment by Wstunes** [comment]
Failing callstack
48 passing (5m)
  1 failing
  1) Editor
       Public-key
         Should download public-keys when possible
           x5c:
     Error: Timeout of 35000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

It doesn't seem  I caused it.

**Comment by Wstunes** [comment]
@sebadoom  Could you have a look at this PR?

**Comment by sebadoom** [comment]
Seems OK, though I cannot give you an exact date for the merge. Cheers!

**Comment by Wstunes** [comment]
@sebadoom  do you have a fixed time reviewing PRs and merging? like once a week?

**Comment by sebadoom** [comment]
No.

**Comment by Wstunes** [comment]
Hope it can be merged in time

**Comment by Wstunes** [comment]
It's been a week. Could you review it and get it merged? @sebadoom

**Comment by sebadoom** [comment]
In 10ef8a919a75c2c1b0e0a69bfbb3dc0a4f055d33

For future reference: there is not definite timeline for merging PRs.

**Pull request closed without merging**
