### PR TITLE
Add Erlang emedia-project/jwerl

### PR DESCRIPTION
**Pull request by astro**

### CODE REVIEW

**Comment by astro** [comment]
Ping.

**Comment by fabianTMC** [comment]
Is there a reason why this was not merged?

**Comment by sebadoom** [comment]
The Erlang logo does not look good. Could you fix this so we can get this merged? Thanks.

screenshot from 2017-12-04 12-58-39

**Comment by sebadoom** [comment]
In 8feb311.

Thank you for your contribution.

**Pull request closed without merging**
