### PR TITLE
Add bryanjos/joken lib and allow filter by Elixir

### PR DESCRIPTION
**Pull request by optikfluffel**

### CODE REVIEW

**Comment by bryanjos** [comment]
@optikfluffel the joken version should be bumped up to 1.0 now

**Comment by optikfluffel** [comment]
Looks like Travis is having [problems downloading PhantomJS](https://travis-ci.org/jsonwebtoken/jsonwebtoken.github.io/builds/130094446#L190-L212) o.0

PS:
Sorry I'm Late

**Comment by optikfluffel** [comment]
🎉

**Comment by chipitsine** [comment]
probably it makes sense to cache npm

cache:
  directories:
    - node_modules

**Comment by optikfluffel** [comment]
@chipitsine #162

**Pull request merged**
