### PR TITLE
Add Delphi library

### PR DESCRIPTION
**Pull request by paolo-rossi**

### CODE REVIEW

**Comment by pose** [comment]
Thanks for your contribution @paolo-rossi. One detail, I'm unable to see the Delphi logo right:

image

Do you think you can make it look like the rest of the logos?

**Comment by paolo-rossi** [comment]
Hi Alberto,

I think I missed the rounded background, I'll add right away... 


Thanks,
Paolo.

**Comment by paolo-rossi** [comment]
Alberto, 

I've reworked and tested the new logo and it appears to be ok...

**Comment by pose** [comment]
@paolo-rossi, great thanks. I'll be merging the PR between today and tomorrow. Sorry for the delay.

**Comment by pose** [comment]
Manually merged, thanks!

**Pull request closed without merging**
