### PR TITLE
Add C++ Library

### PR DESCRIPTION
**Pull request by troian**
https://github.com/troian/josepp

Signed-off-by: Artur Troian <troian.ap@gmail.com>

### CODE REVIEW

**Comment by troian** [comment]
Any chance get this merged?

**Comment by sebadoom** [comment]
We are going to look into it soon. Thanks.

**Comment by sebadoom** [comment]
Missing C++ logo, tracking here: https://github.com/jsonwebtoken/jsonwebtoken.github.io/issues/278

**Comment by sebadoom** [comment]
In 96911fe

Thank you for your contribution.

**Pull request merged**
