### PR TITLE
Modern C++14  extensible library

### PR DESCRIPTION
**Pull request by arun11299**
A C++-14 library with pythonic interface to work with JWT.
Provides both error-code and exception based error reporting.
A modern C++ way of writing code.

### CODE REVIEW

**Comment by arun11299** [comment]
The above failure might be due to missing include in index.jade which I have added now. Can someone check if it is still failing ? Or how to restart the travis build ?

**Comment by arun11299** [comment]
Would be glad to have some comment or help here.

**Comment by sebadoom** [comment]
Hello, thank you for your contribution. Disregard the results from CI, it is broken for the time being. I will take a look at this PR soon. Thanks again.

**Comment by arun11299** [comment]
Oh, great! Thanks @sebadoom .

**Comment by sebadoom** [comment]
In be1e194.

Thank you for your contribution.

**Pull request closed without merging**
