### PR TITLE
Remove ECDSA from namshi/jose

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
According to https://github.com/namshi/jose/issues/94, the implementation is non-conformant and broken.

### CODE REVIEW

**Comment by Oxmoze** [comment]
You are absolutely right: that library produces wrong signatures and rejects all valid ones.

The issues #98 and #101 need to be implemented to verify if libraries are compliant with the RFCs.
At least, all examples from the [RFC7520](https://tools.ietf.org/html/rfc7520) must pass.

**Comment by sebadoom** [comment]
Fixed in 3e67a14. Please note that the PR was wrong (removing the lines is not what was required here). In any case, thank you for your contribution.

**Comment by Spomky** [comment]
By the way, this library is [now unmaintained](https://github.com/namshi/jose#deprecation-notice) and should be removed from the list.

**Comment by sebadoom** [comment]
Thank you for your report, Spomky. We are planning to do a review to find unmaintained libraries and remove them. This is tracked in issue #277. However, thanks to your report we can remove this library before reaching that issue. Thanks again.

**Comment by sebadoom** [comment]
Removed in 3a7c00d

**Pull request closed without merging**
