### PR TITLE
add  28-Scheme

### PR DESCRIPTION
**Pull request by guenchi**
add  28-Scheme

### CODE REVIEW

**Comment by Sambego** [comment]
Hey @guenchi, looks like image you added is actually a base64 hash of a `.png` file inside an `.svg` file. Could you convert it to a "real" `.svg` file?

**Comment by guenchi** [comment]
sorry, @Sambego i don't really know how to do a SVG image ...

**Comment by Sambego** [comment]
You can create `.svg` images in most vector based graphic editors.
Some examples of these programs are
- Adobe Illustrator
- Sketch
- Inksape

You can also use an online editor like https://www.vecteezy.com/editor.

**Comment by Sambego** [comment]
Closing due to inactivity.

**Pull request closed without merging**
