### PR TITLE
Adding jjwt to the list of java libraries

### PR DESCRIPTION
**Pull request by omgitstom**

### CODE REVIEW

**Comment by jcarvalho** [comment]
:+1:

**Comment by geoand** [comment]
:+1:

**Comment by MartinSnyder** [comment]
+1

**Comment by danilobuerger** [comment]
:+1:

**Comment by kag0** [comment]
+1

**Comment by lhazlewood** [comment]
:+1:

**Comment by dogeared** [comment]
:+1:

**Comment by josebarrueta** [comment]
+1

**Comment by bretterer** [comment]
:+1:

**Comment by woloski** [comment]
looks like we already merged the other one

**Comment by raunak** [comment]
https://camo.githubusercontent.com/a2840914d539225aaf8d395397d8dbc488a0740d/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663434642e706e67

**Pull request closed without merging**
