### PR TITLE
Harbour JWT Class

### PR DESCRIPTION
**Pull request by matteobaccan**
Hi

I have added the JWT classes for Harbour language

ciao
matteo

### CODE REVIEW

**Review by Sambego — APPROVED** [review]

**Review by Sambego — CHANGES_REQUESTED** [review]
Ciao Matteo!

Can you please add the logo with a round white background, it currently looks like this:
Screenshot 2022-03-14 at 09 48 33

**Comment by matteobaccan** [comment]
Ciao

ok, I'll change it

ciao
matteo

**Comment by matteobaccan** [comment]
Hi

I have changed the icon.
Tell me if now it's ok

ciao
matteo

**Comment by Sambego** [comment]
Grazie Matteo!

Your library will be live on jwt.io in a few minutes.

**Pull request merged**
