### PR TITLE
[DO NOT MERGE] Code Yellow - HelloBar Slider

### PR DESCRIPTION
**Pull request by pabloalvarezauth0**
This will add a hellobar.com slider on the bottom left of the homepage linking it to our contact us page.

### CODE REVIEW

**Comment by Sambego** [comment]
This PR only updates the `package-lock.json' file, did you forget to commit different changes?

**Comment by pabloalvarezauth0** [comment]
@Sambego Sorry I was making a PR to test the waters and see if there are stage/review environments made for PR's so I can do some testing.

Is there such a thing?

**Comment by Sambego** [comment]
There's no staging environment, you can set up the project locally to test.

**Comment by pabloalvarezauth0** [comment]
Closing PR Stub - will open when there are changes.

**Pull request closed without merging**
