### PR TITLE
spomky-labs/jose

### PR DESCRIPTION
**Pull request by Spomky**
Hi,

This PR adds my PHP library (it replaces my old PR #41).

Please note that it supports `Encryption`, `Decryption`, `JWK` and `JWKSet` you want to start to track (see #94).
To avoid misalignment as this PR adds extra lines, I moved my library and all other PHP libraries at the end to keep them together.

Another last note: [RFC7520](https://tools.ietf.org/html/rfc7520) test vectors are fully implemented as suggested by #98 and all tests pass.

### CODE REVIEW

**Comment by Spomky** [comment]
Is there any reason for this PR not to be merged?

**Comment by Spomky** [comment]
Is there a chance to get this merged?)

**Comment by Spomky** [comment]
Ping @pose

**Comment by pose** [comment]
Hi @Spomky, Since I left Auth0, I no longer maintain jwt.io . @rolodato can you take a look?

**Comment by woloski** [comment]
I will take care

**Comment by woloski** [comment]
This basically breaks the whole layout. I will only include the stuff that is included in the other libraries.

**Comment by Spomky** [comment]
Thanks!

You are right this PR breaks the layout. That is why I moved it at the end of the page.
Anyway, I noted you removed that stuff. I will propose another PR depending on the #94 status.

**Pull request merged**
