### PR TITLE
Adding lcobucci/jwt as a PHP lib

### PR DESCRIPTION
**Pull request by lcobucci**

### CODE REVIEW

**Comment by lcobucci** [comment]
Rebased, fixed and ready 2 go :smile:

**Comment by lcobucci** [comment]
@pose do you guys need any help to merge the PRs?

**Comment by lcobucci** [comment]
Rebased again to be compatible with site update.

**Comment by lcobucci** [comment]
@beneliflo and @rickyrauch is there anything else I can do?

**Comment by pose** [comment]
Manually merged. Thanks @lcobucci!

**Comment by lcobucci** [comment]
Yay! Thanks :smile:

**Pull request closed without merging**
